name: fireflutter
description: Connect to the email and SNS login function of Firebase.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 0.4.4
  cloud_firestore: 0.13.4
  firebase_auth: 0.15.0
  google_sign_in: 4.1.4
  flutter_facebook_login: 3.0.0
  #flutter_twitter_login: ^1.1.0
  flutter_twitter_login:
    git:
      url: git://github.com/eudangeld/flutter_twitter_login.git

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #   - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
